package:
  name: "snowflake-ai"
  version: "0.5.5"

source:
  git_rev: v0.5.5
  git_url: https://github.com/illuminairy-ai/snowflake-ai

requirements:
  host:
    - python >=3.8.10,<3.11
    - setuptools
  run:
    - python >=3.8.10,<3.11
    - toml
    - pandas
    - snowflake-connector-python
    - snowflake-snowpark-python
    - psutil
    - cryptography
    - mpmath
    - urllib3
    - requests
    - scikit-learn
    - streamlit
    - pyjwt
    - altair 4.2.2

outputs:
  - name: "snowflake-ai"
    files:
      - lib/python3.10/site-packages/*

about:
  home: https://github.com/illuminairy-ai/snowflake-ai
  license: Apache Software License 2
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "A Snowflake centic Enterprise AI/ML framework with tight integration of popular data science libraries"

extra:
  recipe-maintainers:
    - illuminairy-ai